//
//  MapModels.swift
//  GeoPos
//
//  Created by Matthew on 06.04.2021.
//  Copyright (c) 2021 Ostagram Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import GoogleMaps

enum MapModel {
    // MARK: Use cases
    
    enum StartTracking{
        struct Request {
        }
        struct Response {
        }
    }
    enum StopTracking{
        struct Request {
        }
        struct Response {
        }
    }
    enum LoadTrack{
        struct Request {
        }
        struct Response {
            let track: [Coordinate]
        }
    }
    enum AddCoordinate{
        struct Response {
            let coordinate: Coordinate
        }
    }
    struct ViewModel {
        var startBtnEnable: Bool = true
        var stopBtnEnable: Bool = false
        var routePath: GMSMutablePath?
        var cameraUpdate: GMSCameraUpdate?
        
    }
}
